kpxy: 5.0
kdxy: 1.0

kpz: 8.0
kdz: 5.0
krp: 12.0
kyaw: 5.0

refVelXYKp: 1.0
refVelZKp: 0.5
refVelHeadingKp: 0.5
refVelRateheadingKp: 0.5

pxy_error_max: 5
vxy_error_max: 5
pz_error_max: 0.6
vz_error_max: 1.2
yaw_error_max: 0.7

k_drag_x: 0.0
k_drag_y: 0.0
k_drag_z: 0.0
k_thrust_horz: 0.0

ref_pos_x: 0.0
ref_pos_y: 0.0
ref_pos_z: 3.0
ref_head: 0.0
ref_head_rate: 0.0